#version: '2'
#
#services:
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_PLAINTEXT_LISTENER: yes
#      TOPIC_AUTO_CREATE: "true"
#      DELETE_TOPIC_ENABLE: "true"
#    networks:
#        - kafka-zookeeper
#  kafka1:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - kafka-zookeeper

#  kafka2:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - "9093:9092"
#    environment:
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#    networks:
#      - kafka-zookeeper
version: '2'

services:
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PLAINTEXT_LISTENER: yes
      TOPIC_AUTO_CREATE: "true"
      DELETE_TOPIC_ENABLE: "true"
    networks:
        - kafka-zookeeper

#  kafka2:
#    image: wurstmeister/kafka
#    container_name: kafka2
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_LISTENERS: PLAINTEXT://:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_PLAINTEXT_LISTENER: yes
#      TOPIC_AUTO_CREATE: "true"
#      DELETE_TOPIC_ENABLE: "true"
#    networks:
#      - kafka-zookeeper

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-zookeeper

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "4456:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      - kafka-zookeeper

networks:
  kafka-zookeeper:
    driver: bridge
