apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 8097
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "EXTERNAL://localhost:8097,INTERNAL://kafka1:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"

---
# kafka2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 8098
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "EXTERNAL://localhost:8098,INTERNAL://kafka2:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"

---
# kafka3-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 8099
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "EXTERNAL://localhost:8099,INTERNAL://kafka3:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"